### PR TITLE
Enhancement/35 move all the exceptions in a separate package

### LINKED ISSUE #35: Move all the exceptions in a separate package
Do it after #26

### PR DESCRIPTION
**Pull request by riccardo14**
this closes #35 
merge after #34

### CODE REVIEW

File: flink-jpmml-scala/src/main/scala/io/radicalbit/flink/pmml/scala/api/exceptions/package.scala [hunk 1]
```diff
@@ -21,6 +21,32 @@ package io.radicalbit.flink.pmml.scala.api
...
+    *
+    * @param msg
+    * @param throwable
+    */
+  private[scala] class ModelLoadingException(msg: String, throwable: Throwable)
+      extends RuntimeException(msg, throwable)
+
   /** Prediction failure due to [[io.radicalbit.flink.pmml.scala.api.EmptyEvaluator]]
     *
     * @param msg
```
Comment (spi-x-i) [inline flink-jpmml-scala/src/main/scala/io/radicalbit/flink/pmml/scala/api/exceptions/package.scala]: Please, can you remove `@param` bullets if not specified? Herein it doesn't make so much sense to insert them.

**Review by spi-x-i — CHANGES_REQUESTED** [review]

**Review by francescofrontera — APPROVED** [review]

**Review by spi-x-i — APPROVED** [review]
